BEGIN;


CREATE TABLE public.activation_email
(
    id integer NOT NULL,
    activation_code character varying(255) NOT NULL,
    company_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cover_letters
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    content character varying NOT NULL,
    created_date date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.employee_activation
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    company_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_confirmed boolean NOT NULL,
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    company_name character varying(255) NOT NULL,
    domain_email character varying(255) NOT NULL,
    phone_number character varying(11) NOT NULL,
    website_name character varying(255) NOT NULL,
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.experiences
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    working_place character varying NOT NULL,
    "position" character varying NOT NULL,
    started_date date NOT NULL,
    finish_date date,
    created_date date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.images
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    url character varying NOT NULL,
    created_date date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_adverts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_id integer NOT NULL,
    employer_id integer NOT NULL,
    job_titles_id integer NOT NULL,
    description character varying NOT NULL,
    open_job_counter integer NOT NULL,
    application_deadline date NOT NULL,
    is_open boolean NOT NULL,
    created_date date,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    publish_date date NOT NULL,
    salary_min integer NOT NULL,
    salary_max integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seeker
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    identity_number character varying(11) NOT NULL,
    date_of_birth date,
    verify_mernis boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_titles
(
    job_title_id integer NOT NULL,
    job_title_name character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    PRIMARY KEY (job_title_id)
);

CREATE TABLE public.languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    language character varying NOT NULL,
    level integer NOT NULL,
    created_date date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.links
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    name character varying NOT NULL,
    url character varying NOT NULL,
    is_active boolean,
    is_deleted boolean,
    created_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.schools
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    name character varying NOT NULL,
    department character varying NOT NULL,
    start_date date NOT NULL,
    finish_date date NOT NULL,
    created_date date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.skills
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    name character varying NOT NULL,
    created_date date,
    is_active boolean,
    is_deleted boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    created_date date,
    PRIMARY KEY (id)
);

ALTER TABLE public.activation_email
    ADD FOREIGN KEY (company_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.cover_letters
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;


ALTER TABLE public.employee_activation
    ADD FOREIGN KEY (company_id)
    REFERENCES public.employees (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.experiences
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;


ALTER TABLE public.images
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;


ALTER TABLE public.job_adverts
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_adverts
    ADD FOREIGN KEY (job_titles_id)
    REFERENCES public.job_titles (job_title_id)
    NOT VALID;


ALTER TABLE public.job_adverts
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_seeker
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.languages
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;


ALTER TABLE public.links
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;


ALTER TABLE public.schools
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;


ALTER TABLE public.skills
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;

END;
